### PR TITLE
Fix ci failure due to environment variables not being set properly

### PR DESCRIPTION
**Pull request by mohammedzee1000**

### CODE REVIEW

**Comment by bamachrn** [comment]
#dotests

**Comment by bamachrn** [comment]
#dotests

**Comment by bamachrn** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
I dont think this PR can be validated through ci as its change is in the job.yml. So the PR will need to be merged before we can validate it through ci itself.

In the future, we might want to figure out a way to auto validate changes to job.yml.

**Comment by bamachrn** [comment]
PR is run after a merge so it should ideally work

**Comment by bamachrn** [comment]
#dotests

**Pull request merged**
