### PR TITLE
Make loggers more verbose. Fixes #170

### LINKED ISSUE #170: Loggers are not verbose
**Issue**

Currently, loggers are not verbose, and hence useless. It's very difficult to get meaningful debug info and tracebacks from worker logs.

**Fix**

- Update loggers to log with ``exc_info`` == ``True`` to show tracebacks in case of ``CRITICAL``/``FATAL`` logs
- Log extra data, e.g., local variable values, when there is an error with ``extra`` keyword argument
- Format logs properly

### PR DESCRIPTION
**Pull request by rtnpro**

### CODE REVIEW

**Comment by navidshaikh** [comment]
We need this, the CI is blocked due to merge conflicts.

**Comment by rtnpro** [comment]
Rebased and waiting for CI to be green!

**Comment by bamachrn** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests-debug

**Comment by rtnpro** [comment]
#dotests-debug

**Comment by rtnpro** [comment]
#dotests-debug

**Comment by navidshaikh** [comment]
#dotests-debug

**Comment by rtnpro** [comment]
#dotests-debug

**Comment by navidshaikh** [comment]
@rtnpro : ping - do you want to take a look at the CI ? We need this PR in.

**Comment by rtnpro** [comment]
@dharmit @navidshaikh @bamachrn can someone merge this?

**Pull request merged**
