### PR TITLE
Takes off all the existing migrations and prevent creation of migration part of deployment

### PR DESCRIPTION
**Pull request by navidshaikh**
Since its not a good practice to make migrations on prod environments.

### CODE REVIEW

**Comment by navidshaikh** [comment]
@bamachrn @dharmit @mohammedzee1000 : I kept the `migrate` operations as part of ansible scripts, since making migrations should happen prior to deployment however I think we should keep the `migrate` operations as part of ansible itself. This helps eliminate the manual operation errors (say one missed `migrate` step). Also in this patch, we are ensuring `migrate` operation works as expected by removing `ignore_errors` flag.

**Comment by navidshaikh** [comment]
#dotests

**Comment by navidshaikh** [comment]
> I kept the migrate operations as part of ansible scripts, since making migrations should happen prior to deployment however I think we should keep the migrate operation as part of ansible itself.

I tried deployments with mentioned configs however, it could create problems. I tried updating the `migrate` command flags like `python manage.py  --merge` which merges the migrations operations, however it could lead to merge conflicts. I think we should totally, take off the migrations related operations from ansible deployment scripts and have it done manually. Since migrations are not going to be usual operation as compared to usual deployment of service, we can take off the complexity and potential issues that could be involved.

**Comment by navidshaikh** [comment]
#dotests

**Comment by navidshaikh** [comment]
#dotests

**Comment by navidshaikh** [comment]
The scope of PR is now to take off all the migrations and start afresh. For henceforth, its agreed upon to maintain the migrations as we are going to maintain the data of db.

**Comment by navidshaikh** [comment]
#dotests

**Comment by navidshaikh** [comment]
#dotests

**Comment by bamachrn** [comment]
LGTM, only concern is, we are not loosing data upon re-deployment

**Pull request merged**
