### PR TITLE
[Later] Did some refactoring and added more docstrings to index ci

### PR DESCRIPTION
**Pull request by mohammedzee1000**
The refactoring includes adding ability to save the graph in a file and build back the object from the yaml.

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
I would recommend going for further index ci changes here after we have the basic tests for the same merged. They are present 
https://github.com/CentOS/container-pipeline-service/pull/129

**Comment by navidshaikh** [comment]
This PR goes after PR #129

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by rtnpro** [comment]
@mohammedzee1000 ping?

**Pull request closed without merging**
