### PR TITLE
Added cccp.yml files for pipeline index entry

### PR DESCRIPTION
**Pull request by bamachrn**
* Added cccp.yml for server images (cccp-build, cccp-test, cccp-delivery) in /server
* Added cccp.yml for mail server for mail server image in /mail-service

### CODE REVIEW

**Comment by kbsingh** [comment]
@dharmit are you going to consolidate the scanner + linter images into the same app-id ?

**Comment by kbsingh** [comment]
@dharmit ping

**Comment by dharmit** [comment]
Sorry, missed the earlier ping. #34 & PR [20](https://github.com/CentOS/container-index/pull/20) on container-index.

**Comment by kbsingh** [comment]
lgtm

**Pull request merged**
