### PR TITLE
track the container index tests with the rest of the ci jobs

### PR DESCRIPTION
**Pull request by bstinsonmhk**
Let's move the index test job in with the rest of the CI jobs and enable the pull request trigger on the index repo.

### CODE REVIEW

**Comment by bstinsonmhk** [comment]
Not quite ready to merge, but wanted to see if @rtnpro was ok to run jjb across job.yml

**Comment by rtnpro** [comment]
LGTM :+1:

**Comment by rtnpro** [comment]
Looks good to me :+1:

**Comment by mohammedzee1000** [comment]
@bstinsonmhk i guess we can complete this up and have this setup now.

**Comment by bstinsonmhk** [comment]
Ok, I did a jjb run across this job.yml

Let's check the jobs and merge this if everyone's happy.

**Pull request merged**
