### PR TITLE
Removes unnecessary install of python-docker-py for scanner

### PR DESCRIPTION
**Pull request by navidshaikh**

### CODE REVIEW

**Comment by kbsingh** [comment]
how is the worker going to engage with the remote docker instance without the docker client ?

**Comment by navidshaikh** [comment]
> how is the worker going to engage with the remote docker instance without the docker client ?

It can't, however ATM the worker is not involved. No worker is included in the scanner image.

**Comment by navidshaikh** [comment]
Verified the PR by running the resulting scanner over multiple images.
Here is the automated build configured from this PR / branch for new pipeline-container https://hub.docker.com/r/swordphilic/pipeline-scanner/

**Comment by kbsingh** [comment]
@navidshaikh can you rebase to master ?

**Comment by navidshaikh** [comment]
> @navidshaikh can you rebase to master ?

@kbsingh : done.

**Pull request merged**
