### PR TITLE
[CI] Fix copying source code from to openshift node.

### PR DESCRIPTION
**Pull request by rtnpro**

### CODE REVIEW

**Comment by dharmit** [comment]
Umm, not sure if it's just me but I couldn't find the `role_path` variable mentioned in the commit anywhere in the repo. I tried GitHub search on CentOS/container-pipeline-service and also tried `grep -r role_path` on my local copy of the code.

**Comment by rtnpro** [comment]
@dharmit ``role_path`` is an ansible variable :)

**Comment by dharmit** [comment]
Ah cool, didn't know it's a built-in variable. I was looking for it in the `provisions` directory. :)

**Comment by rtnpro** [comment]
Closing this in favor of #168

**Pull request closed without merging**
