### PR TITLE
Setup CI

### PR DESCRIPTION
**Pull request by rtnpro**
Migrated and update CI scripts and added README for it.

Changes:

- migrate CI scripts to ``ci`` dir
- allow testing branch code
- Fix cccp source code
- Improve provisioning scripts
- Bugfixes

### CODE REVIEW

**Comment by kbsingh** [comment]
do these changes map to a job over in ci.centos.org ?

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
@kbsingh can we merge this?

**Comment by kbsingh** [comment]
lgtm

**Pull request merged**
