### PR TITLE
Allow user to specify custom build context.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
This allows user to specify their own build context, other than ., for the dockerfiles.

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by bamachrn** [comment]
#dotests-debug

**Comment by dharmit** [comment]
@mohammedzee1000 Please take a look at below snippet and make necessary changes:

```bash
$ git diff provisions/roles/jenkins/slave/templates/template.json.j2
diff --git a/provisions/roles/jenkins/slave/templates/template.json.j2 b/provisions/roles/jenkins/slave/templates/template.json.j2
index 8255037..cbf5ac2 100644
--- a/provisions/roles/jenkins/slave/templates/template.json.j2
+++ b/provisions/roles/jenkins/slave/templates/template.json.j2
@@ -83,6 +83,11 @@
       "name": "BEANSTALK_SERVER",
       "description": "An url for the server where beanstalkd runs",
       "value": "{{ beanstalk_server }}"
+    },
+    {
+      "name": "BUILD_CONTEXT",
+      "description": "Path for build context",
+      "value": "."
     }
   ],
   "objects": [
```

**Comment by mohammedzee1000** [comment]
#dotests

**Pull request merged**
