### PR TITLE
Added verbose flag to index ci init and changed ci job script.

### PR DESCRIPTION
**Pull request by mohammedzee1000**

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
hmm it doesnt appear the failure was something from PRs side
@bamachrn @rtnpro comments?

**Comment by navidshaikh** [comment]
@mohammedzee1000 : Once the CI is green, we merge the PR.

**Comment by navidshaikh** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
ok to test

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
#dotests

**Pull request merged**
