### PR TITLE
Stops printing command ran on CI console

### PR DESCRIPTION
**Pull request by navidshaikh**
This to minimize the unnecessary text printed on CI console.

### CODE REVIEW

**Comment by dharmit** [comment]
I've been doing CI debugging lately for a few PRs that fail CI check. And it's really helpful to have info about the command that failed CI check. I believe that with this changeset, we stop logging the command that fails. 

I vote to not merge this PR. While I agree that we need to reduce the amount of logs being printed on console, I vote against going ahead with this particular one.

**Comment by navidshaikh** [comment]
> And it's really helpful to have info about the command that failed CI check.

@dharmit 
if you check, https://github.com/CentOS/container-pipeline-service/blob/master/ci/lib.py#L111 , we are printing the command if it there are any errors in executing it.

**Comment by navidshaikh** [comment]
@dharmit 

Some more to help understand, we do print the command failed in CI

```
Exception: Run Command Error for: ssh -t -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no  root@n6.gusty 'cat /tmp/deploy.logs'
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added 'n6.gusty,172.19.2.134' (ECDSA) to the list of known hosts.
cat: /tmp/deploy.logs: No such file or directory
```

from https://ci.centos.org/job/centos-container-pipeline-service-ci-pr/1473/console

**Comment by dharmit** [comment]
@navidshaikh thanks. As long as we're printing the command that failed along with why it failed, I'm fine. 👍 

@bamachrn can you take a look once?

**Comment by bamachrn** [comment]
@navidshaikh IIUC this PR is for making sure we are not printing the commands before running them. and if some command fails it is printed in the exception right?

**Comment by bamachrn** [comment]
wow! this is merged.

**Comment by navidshaikh** [comment]
> if some command fails it is printed in the exception right?

Right. Also mentioned in earlier comments https://github.com/CentOS/container-pipeline-service/pull/388#issuecomment-350221937

**Pull request merged**
