### PR TITLE
Adds docker system prune in cleanup utility

### PR DESCRIPTION
**Pull request by navidshaikh**
This will remove:
	- all stopped containers
	- all volumes not used by at least one container
	- all networks not used by at least one container
	- all dangling images

### CODE REVIEW

**Comment by bamachrn** [comment]
this looks good. but can we delete the volumes and all after removing the container while scanning them?

**Comment by navidshaikh** [comment]
>  but can we delete the volumes and all after removing the container while scanning them?

We can! I think you missed PR #452.

**Comment by navidshaikh** [comment]
#dotests

**Comment by navidshaikh** [comment]
#dotests

**Comment by navidshaikh** [comment]
#dotests

**Comment by navidshaikh** [comment]
#dotests

**Comment by bamachrn** [comment]
LGTM, Merging

**Pull request merged**
