### PR TITLE
Commenting out garbage collection steps to fix missing images.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
This is a temporary measure until i can find a more suitable
solution for this problem.

### CODE REVIEW

**Comment by navidshaikh** [comment]
@dharmit @bamachrn : The CI has passed and PR is waiting for your review.

**Comment by dharmit** [comment]
> @dharmit @bamachrn : The CI has passed and PR is waiting for your review.

This had to be tested by me on DevCloud. Deployment just finished for me and am working on testing this PR now.

@bamachrn ignore this PR. I'll review and merge if it looks good to me.

**Comment by bamachrn** [comment]
sure. thanks @dharmit

**Comment by dharmit** [comment]
@mohammedzee1000 I think this is not expected:

```bash
# python __init__.py -r 172.29.33.21 -i https://github.com/dharmit/container-index                                                     
Cloning container index...                 
Cloning into './c_i'...                    
remote: Counting objects: 1234, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 1234 (delta 22), reused 24 (delta 13), pack-reused 1198
Receiving objects: 100% (1234/1234), 227.68 KiB | 0 bytes/s, done.                    
Resolving deltas: 100% (794/794), done.    
Gathering registry metadata...             
Going through the index.                   
Images to Remove :                         
{u'che-stacks/maven33': [u'ZWQ4YWJiMDgwNW', u'latest'], u'centos/centos': [u'MTYwZGM1MjJmY2'], u'devcloud/wget': [u'NTFlZmQ2ODkzMT', u'latest'], u'dharmit/freegeoip': [u'NDY3NTZiMzAwMG', u'MzA5ZDZjZTgxNW'], u'dharmit/nsq': [u'MTNjODkwNjIwOD'], u'centos/moodle': [u'ZTQ4MzlmMjk0OT', u'3.1'], u'devcloud/outdated': [u'ZWI2N2RiZjg4ZD', u'latest']}  
[root@jenkins-master cleanup_registry]# vi garbagecollector.py                        
[root@jenkins-master cleanup_registry]# grep -A3 'subs =' garbagecollector.py
#            subs = glob(tags + "/*")
#            if len(subs) <= 0:
#                lib.rm(namespace_path)

**Comment by bamachrn** [comment]
@dharmit are you in position to test this works as expected?

**Pull request merged**
