### PR TITLE
Add atomic scan based image scanner

### PR DESCRIPTION
**Pull request by dharmit**
@kbsingh @bamachrn ping

### CODE REVIEW

**Comment by dharmit** [comment]
As far as migrating existing scanner to use `atomic scan` based scanner is concerned, I've not replaced the code in `beanstalk_worker` directory yet. This is to ensure we can do some testing (which I've already done and faced no issues on Devcloud) before we push it further.

Let me know your thoughts.

**Comment by kbsingh** [comment]
Can we use the existing beanstalkc.py in the repo rather than carry another copy here ?

**Comment by bamachrn** [comment]
This looks good to me. We need to figure out some way to use same beanstalkc.py for the workers, this is the reason I kept all the workers in the same directory. Scan runs separately and keeping scaling in mind this looks good.

**Comment by dharmit** [comment]
This worker should eventually replace the one in `beanstalk_worker` directory. Once that's done, we won't need to carry the second copy of `beanstalkc.py`.

**Comment by kbsingh** [comment]
Lgtm

**Pull request merged**
