### PR TITLE
Reserve duffy nodes for debugging when CI job fails.

### PR DESCRIPTION
**Pull request by rtnpro**

### CODE REVIEW

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
@kbsingh LGTM :+1:

**Comment by kbsingh** [comment]
once a specific node has been marked as 'Failed' - whats the plan for returning those back ? are we tracking the ssid's somewhere for these jobs ?

**Comment by kbsingh** [comment]
@rtnpro ping

**Comment by rtnpro** [comment]
@kbsingh currently, I am printing only the nodes info in the consoloe output, right now. However, I can print the ``ssid`` in the console output as well. As of now, I was depending on the CICO infrastructure to reclaim the nodes after 6 hours. 6 hours will be a plenty amount of time to debug.

However, it'd be great to have a way to say that I'm done with debugging, and return the machines. Any idea around it?

**Comment by rtnpro** [comment]
@kbsingh ping?

**Comment by kbsingh** [comment]
working around this on the cico side, so we should be ok to merge.

**Pull request merged**
