### PR TITLE
Added script to cleanup registry based on diff with index.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Signed-off-by: Mohammed Zeeshan Ahmed <mohammed.zee1000@gmail.com>

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
#dotests-debug

**Comment by mohammedzee1000** [comment]
#dotests-debug

**Comment by mohammedzee1000** [comment]
#dotests-debug

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
#dotests-debug

**Comment by bamachrn** [comment]
#dotests-debug

**Comment by bamachrn** [comment]
it seems internal registry is not coming up properly
```
The push refers to a repository [172.30.220.105:5000/53b1a8ddd3df5d4fd94756e8c20ae160e565a4b339bfb47165285955/python]
Get https://172.30.220.105:5000/v1/_ping: http: server gave HTTP response to HTTPS client
```
doing a retest

**Comment by bamachrn** [comment]
#dotests-debug

**Comment by mohammedzee1000** [comment]
I dont remember changing anything related to internal registry. Any idea why this is happening?
@bamachrn ^

**Comment by bamachrn** [comment]
#dotests-debug

**Comment by bamachrn** [comment]
#dotests

**Pull request merged**
