### PR TITLE
Updated delivery worker to tag library images without the appid.

### PR DESCRIPTION
**Pull request by mohammedzee1000**

### CODE REVIEW

**Comment by bamachrn** [comment]
LGTM 👍

**Comment by bamachrn** [comment]
@mohammedzee1000 this will require chekcing the image build with library tag. as CI does not verify it with library images

**Comment by bamachrn** [comment]
@navidshaikh he has to put in the file called library. And we are making sure appid matches the file name in index-CI

**Comment by mohammedzee1000** [comment]
@bamachrn understood

**Comment by mohammedzee1000** [comment]
https://github.com/CentOS/container-pipeline-service/pull/274 this will take care of making app-id and filename matching compulsory @bamachrn

**Comment by bamachrn** [comment]
#dotests

**Pull request merged**
