### PR TITLE
Added transformation script for indexd to indexyml file.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
Also, updated the jenkins template to use index.d in shell.

Relies on https://github.com/CentOS/container-index/pull/24

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
Changes validated in all-in-one setup

**Comment by bamachrn** [comment]
#dotests

**Comment by bamachrn** [comment]
#dotests

**Comment by bamachrn** [comment]
#dotests

**Pull request merged**
