### PR TITLE
Fixing pattern so that yaml files are also picked up.

### PR DESCRIPTION
**Pull request by mohammedzee1000**
This PR ensures that index ci can pick up on files ending with yaml and not just yml extension.

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
@bamachrn @navidshaikh ^

**Comment by navidshaikh** [comment]
@mohammedzee1000 : No description of the PR! PRs should always set context via description field.

**Comment by mohammedzee1000** [comment]
@navidshaikh updated, ptal

**Comment by bamachrn** [comment]
can we think of keeping both, so that the existing ones does not break?

**Comment by mohammedzee1000** [comment]
@bamachrn it should not break charlie's pr (https://github.com/CentOS/container-index/pull/271) updates all files currently in index to yaml.

**Comment by bamachrn** [comment]
I would say we keep both in the check for now. later after everyone moves to yaml, we can go for validating only yaml. otherwise this will cause a huge change across all the repositories we are having in container-index.

**Comment by mohammedzee1000** [comment]
@bamachrn understood. I am not updating the matching for cccp yet. Only the index file we control and those can be updated by us immediately.

**Pull request merged**
