### PR TITLE
Filters expected deviations in rpm-verify scanner

### PR DESCRIPTION
**Pull request by navidshaikh**
This PR adds provision in rpm-verify atomic scanner to filter the
  results. There are directories in system which are expected to be modified.
  This PR filters such directories from results.
  Following are the filtered directories:
  `["/var", "/run", "/media", "/mnt", "/tmp","/proc", "/sys", "/boot"]`

### CODE REVIEW

**Comment by navidshaikh** [comment]
new image built with this PR is `swordphilic/scanner-rpm-verify`

**Comment by navidshaikh** [comment]
Verified the PR.

**Comment by dharmit** [comment]
LGTM :+1:

**Comment by dharmit** [comment]
@navidshaikh can you please rebase? I'll merge it.

**Pull request merged**
