### PR TITLE
Refactored tests into unit tests and functional tests.

### PR DESCRIPTION
**Pull request by mohammedzee1000**

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
Doesnt look like failure is from my code @rtnpro wdyt?

**Comment by rtnpro** [comment]
@mohammedzee1000 can you rebase this?

**Comment by mohammedzee1000** [comment]
rebased

**Comment by navidshaikh** [comment]
@mohammedzee1000 : is this good to go ?

**Comment by mohammedzee1000** [comment]
@navidshaikh yes, the tests will come in seperate PR.

**Pull request merged**
