### PR TITLE
Prevents logging unnecessary recurring queue operational messages

### LINKED ISSUE #439: Remove unnecessary recurring beanstalkd queue operation messages to save logging space
An example of issue : 

```
$ tail -f -n 100 /srv/pipeline-logs/cccp.log
[2018-01-18 11:19:22,525] build-worker p1 36 DEBUG - No job in queue
[2018-01-18 11:19:31,746] test-worker p1 57 DEBUG - Waiting to get data from tube: start_test...
[2018-01-18 11:19:31,752] test-worker p1 36 DEBUG - No job in queue
[2018-01-18 11:19:36,918] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:19:36,924] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:20:06,944] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:20:06,951] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:20:36,957] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:20:36,962] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:21:06,992] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:21:06,999] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:21:37,001] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:21:37,006] tracking p14320 36 DEBUG - No job in queue
 DEBUG - No job in queue
[2018-01-18 11:21:34,084] dispatcher p1 57 DEBUG - Waiting to get data from tube: master_tube...
[2018-01-18 11:21:34,088] dispatcher p1 36 DEBUG - No job in queue
[2018-01-18 11:21:34,088] delivery-worker p1 57 DEBUG - Waiting to get data from tube: start_delivery...
[2018-01-18 11:21:34,093] delivery-worker p1 36 DEBUG - No job in queue
[2018-01-18 11:21:52,677] build-worker p1 57 DEBUG - Waiting to get data from tube: start_build...
[2018-01-18 11:21:52,683] build-worker p1 36 DEBUG - No job in queue
[2018-01-18 11:22:07,036] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:22:07,049] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:22:37,079] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:22:37,085] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:23:07,099] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:23:07,105] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:23:37,134] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:23:37,139] tracking p14320 36 DEBUG - No job in queue
024] test-worker p1 36 DEBUG - No job in queue
[2018-01-18 11:24:07,170] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:24:07,183] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:24:37,186] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:24:37,192] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:25:07,198] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:25:07,205] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:25:37,229] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:25:37,233] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:26:07,248] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:26:07,255] tracking p14320 36 DEBUG - No job in queue
 tube: start_build...
[2018-01-18 11:26:22,897] build-worker p1 36 DEBUG - No job in queue
[2018-01-18 11:26:37,285] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:26:37,290] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:27:07,309] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:27:07,315] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:27:37,345] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:27:37,351] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:28:07,381] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:28:07,389] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:28:37,412] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:28:37,418] tracking p14320 36 DEBUG - No job in queue
cher p1 57 DEBUG - Waiting to get data from tube: master_tube...
[2018-01-18 11:28:34,469] dispatcher p1 36 DEBUG - No job in queue
[2018-01-18 11:28:53,069] build-worker p1 57 DEBUG - Waiting to get data from tube: start_build...
[2018-01-18 11:28:53,074] build-worker p1 36 DEBUG - No job in queue
[2018-01-18 11:29:02,350] test-worker p1 57 DEBUG - Waiting to get data from tube: start_test...
[2018-01-18 11:29:02,356] test-worker p1 36 DEBUG - No job in queue
[2018-01-18 11:29:07,448] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:29:07,455] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:29:37,484] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:29:37,489] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:30:07,520] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:30:07,527] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:30:37,548] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:30:37,553] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:31:07,569] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:31:07,576] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:31:04,568] delivery-worker p1 57 DEBUG - Waiting to get data from tube: start_delivery...
[2018-01-18 11:31:04,572] dispatcher p1 57 DEBUG - Waiting to get data from tube: master_tube...
[2018-01-18 11:31:04,574] delivery-worker p1 36 DEBUG - No job in queue
[2018-01-18 11:31:04,578] dispatcher p1 36 DEBUG - No job in queue
[2018-01-18 11:31:23,232] build-worker p1 57 DEBUG - Waiting to get data from tube: start_build...
[2018-01-18 11:31:23,241] build-worker p1 36 DEBUG - No job in queue
[2018-01-18 11:31:37,607] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:31:37,612] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:32:07,632] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:32:07,646] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:32:37,677] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:32:37,682] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:33:07,712] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:33:07,720] tracking p14320 36 DEBUG - No job in queue
BUG - No job in queue
[2018-01-18 11:33:37,744] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:33:37,750] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:34:07,758] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:34:07,772] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:34:37,789] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:34:37,795] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:35:07,826] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:35:07,833] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:35:37,861] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:35:37,867] tracking p14320 36 DEBUG - No job in queue
18-01-18 11:35:53,552] build-worker p1 36 DEBUG - No job in queue
[2018-01-18 11:36:07,897] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:36:07,905] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:36:37,935] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:36:37,940] tracking p14320 36 DEBUG - No job in queue
[2018-01-18 11:37:07,951] tracking p14320 57 DEBUG - Waiting to get data from tube: tracking...
[2018-01-18 11:37:07,957] tracking p14320 36 DEBUG - No job in queue
```

As we can see, the service logs these queue operational messages in log file, causing
  - unnecessary log file increased size
  - unnecessary hurdle while debugging logs

### PR DESCRIPTION
**Pull request by navidshaikh**
Fixes #439

  To optimize the log files sizes, enhance readability of log files.

### CODE REVIEW

**Comment by navidshaikh** [comment]
#dotests

**Comment by navidshaikh** [comment]
#dotests

**Comment by navidshaikh** [comment]
#dotests

**Comment by navidshaikh** [comment]
> I would say we should log in case of state change, may be connected or getting disconnected.

@bamachrn : Please update your review remark.
It's already there. Expand the file check for the unedited changed of file, and logging for strings "Lost connection.." and "Connection...initialized".

**Comment by bamachrn** [comment]
#dotests

**Comment by navidshaikh** [comment]
#dotests

**Pull request merged**
