### PR TITLE
App id and filename check mismatch is now a warning

### PR DESCRIPTION
**Pull request by mohammedzee1000**

### CODE REVIEW

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by mohammedzee1000** [comment]
We have CI success here @bamachrn

**Comment by mohammedzee1000** [comment]
#dotests

**Comment by bamachrn** [comment]
LGTM

**Pull request merged**
