### PR TITLE
Allow configuring log level on deployment.

### PR DESCRIPTION
**Pull request by rtnpro**

### CODE REVIEW

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
#dotests-debug

**Comment by navidshaikh** [comment]
@rtnpro : Please give an example of configuring the log level at deployment ? I think its going to be the variable in hosts.sample and same command ?

**Comment by rtnpro** [comment]
@navidshaikh yes, all you need to do is set ``log_level`` in your inventory file.

**Comment by rtnpro** [comment]
#dotests-debug

**Comment by rtnpro** [comment]
#dotests

**Comment by rtnpro** [comment]
https://ci.centos.org/job/centos-container-pipeline-service-ci-pr/951/ passed! @bamachrn review and merge.

**Pull request merged**
